// Generated by CoffeeScript 1.7.1
(function() {
  var LeapChat, enhanceChatWindows, leapChat;

  console.log("I am chrome extension");

  LeapChat = (function() {
    function LeapChat() {}

    LeapChat.prototype.enhance = function(jqElem) {
      var canvasHeight;
      canvasHeight = 120;
      jqElem.addClass('leap-facebook-chat');
      return jqElem.append("<div style='width: 100%; height: " + canvasHeight + "px; background: black; z-index: 100; position: absolute; left: 0; top: -" + canvasHeight + "px;'></div>");
    };

    return LeapChat;

  })();

  leapChat = new LeapChat();

  enhanceChatWindows = function() {
    console.log("I am enhancing chat window");
    return leapChat.enhance($('.fbNubFlyout .fbNubFlyoutTitlebar.titlebar:not(.leap-facebook-chat)'));
  };

  setInterval(enhanceChatWindows, 1500);

}).call(this);
